fix: concurrency cancel

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -11,6 +11,10 @@ permissions:
     contents: read
     packages: write
 
+concurrency:
+  group: production
+  cancel-in-progress: true
+
 jobs:
     build:
         if: >-
@@ -66,3 +70,16 @@ jobs:
         - name: Show deployed verison
           run: |
             echo "Version: ${{github.sha}}"
+        
+        - name: Health check
+          run: |
+            for i in {1..20}; do
+              curl -f http://${{secrets.EC2_HOST}}/health/  && exit 0
+              echo "waiting for application to restart"
+
+              sleep 5
+
+            done
+            echo "Application startup failed"
+            exit 1
+
